### ISSUE TITLE
[ITEM 8] finalizer, cleaner와 System.gc의 차이

### ISSUE THREAD

**Issue by hgh1472** [hgh1472/ReadingStudy#10]
아이템 8을 읽었을 때, 직접 사용해본 적은 없지만 `finalizer`와 `cleaner`가 자원 회수와 관련있다고 느꼈습니다.
`System.gc()`는 가비지 컬렉션을 실행하는 것으로 알고 있는데, `finalizer, cleaner`와 `System.gc()`의 차이가 궁금합니다.

**Comment by kahyun0255** [comment]
finalizer, cleaner는 책에 많이 나와있지만 System.gc()는 잘 나와있지 않은것같아 System.gc()에 대해 우선 찾아보았습니다.

## System.gc()
- GC는 더 이상 사용하지 않는 메모리 영역을 알아서 해제해 가용상태로 돌려주는 역할을 하는데, 실행 조건이 일정하지 않습니다.
- System.gc() 메소드를 직접 호출해도 실제 gc가 작동할지는 미지수(바로 실행됨을 보장하지 않음)

## 차이
JVM은 GC 실행 시 해제 대상 객체(Object)를 수집하기 전 Finalize를 처리해야 한다. Finalizer 참조 객체는 GC 발생시 즉시 메모리에서 수집되지 않고 Finalize 처리를 위한 대기 큐에 들어간다. 그 다음 FinalizerThread에 의해 Finalize 처리 후  GC 발생시 제거된다.

즉, finalizer와 cleaner는 가비지 컬렉션될 때 호출되는 메서드들, System.gc는 가비지컬렉션을 실행해달라고 JVM에 요청하는 메서드 인 것 같아요. 그렇기때문에 finalizer와 cleaner는 객체의 특정 자원 정리 작업을 수행하는 코드가 들어가겠지만, System.gc()는 객체의 특정 자원 정리 작업을 수행하지 않고 요청만 하는 메서드인것 같습니다.

---
참고 : [https://velog.io/@recordsbeat/Garbage-Collector-제대로-알기](https://velog.io/@recordsbeat/Garbage-Collector-%EC%A0%9C%EB%8C%80%EB%A1%9C-%EC%95%8C%EA%B8%B0), https://kkambi.tistory.com/159, https://www.brainz.co.kr/recent-story/view/page/4/id/218#u

**Comment by hgh1472** [comment]
오호 감사합니다!
