### ISSUE TITLE
[ITEM 11] HashMap에서의 Key

### ISSUE THREAD

**Issue by hgh1472** [hgh1472/ReadingStudy#12]
HashMap에서 (Key, Value) 형태로 자료가 저장되는데, 이 때 Key값이 각 객체의 주소값으로 분류된다고 대충 짐작하고 있었습니다.
이 때 객체 주소값이 아닌 hashCode의 값으로 Key값을 분류하는지 궁금해요!
만약 아니라면, hashCode가 사용될 수 있는 상황이 어떤 것이 있을까요??

**Comment by l2yujw** [comment]
### 결론은 Hash 형제들은 hashCode도 같이 등록하며 hash와 key 둘다 확인을 해서 분류를 합니다.
### 1. 객체를 비교할 때 드는 비용을 낮추기 위한 상황에서 사용을 하게 됩니다
### hashCode 값을 사용하여 특정 객체가 저장될 위치를 즉시 계산할 수 있기 때문입니다
### 2. 객체를 매핑하며 객체를 찾을 때 사용합니다.
### 3. 객체에 고유한 식별자 역할을 해줍니다.

추가적인 도움이 됐으면 해서 이런저런 내용도 설명드리겠습니다.
hashCode가 기본적으로 생성되는 방식은 모든 것들이 챙겨가는 Object 객체한테서 나옵니다.
Object 객체에서 
``` java
public native int hashCode();
```
제공하고 이는 JNI를 사용해서 네이티브로 구현되었다는 것을 나타냅니다

---
JNI : Java Native Interface
자바 가상머신(JVM)위에서 실행되고 있는 자바코드가 네이티브 응용 프로그램(하드웨어와 운영 체제 플랫폼에 종속된 프로그램들) 그리고 C, C++ 그리고 어셈블리 같은 다른 언어들로 작성된 라이브러리들을 호출하거나 
반대로 호출되는 것을 가능하게 하는 프로그래밍 프레임워크입니다.

위의 hashCode는 실행중에 객체의 유일한 integer값을 반환한다고 하고
 Object 클래스에서는 heap에 저장된 객체의 메모리 주소를 반환한다고 합니다 
 항상 그런건 아니라고 하네요

---

즉, 일반 키를 가지고 해시값을 찾으면 같은 내용의 객체나 값을 넣어도 다른 해시가 적용이 된다는 의미입니다.
예를 들어 책의 예시로 잡으면, 
``` java
m.put(new PhoneNumber(707, 867, 5309), "제니"); // 주해시코드(주소) 6245.... 대입할게
m.get(new PhoneNumber(707, 867, 5309)); // 새로 주해시코드(주소) 1944.... 주라
```
없기 때문에 안줍니다.

그러면 어떻게 해야 할까 하면
hashCode를 재정의 해야 합니다.
어떻게 재정의를 하고 왜 그렇게 재정의를 해야하는지 설명드리겠습니다.

Object 클래스가 아닌 final class인 Objects에서 hash 메서드에 hash를 생성할 재료들을 넣어서 해시코드를 같은 계산 안에서 생성을 해야 합니다.
``` java
@Override
public int hashCode() {
	return Objects.hash(클래스변수, 클래스변수....);
}
```
이런식으로 말이죠
그래야 같은 값으로 같은 해시를 받을 수 있습니다.

내부 동작을 한번 보겠습니다
Objects에 hash를 들어가보면
``` java
public static int hash(Object... values) {
        return Arrays.hashCode(values);
}
```
값들을 다 받아서 Arrays의 hashCode 메서드에 다 떠넘깁니다

Arrays의 hashCode를 가보면
``` java
public static int hashCode(Object a[]) {
        if (a == null)
            return 0;

        int result = 1;

        for (Object element : a)
            result = 31 * result + (element == null ? 0 : element.hashCode());

        return result;
}
```
이런식으로 넘겨준 values들을 a[]로 받아서 iterator 돌리면서 더하고 재귀하는 방식으로 해시코드를 생성해주는 것 같습니다.
그리고 element.hashCode()에는 String이 들어가서 같은 값이면 같은 hash가 나오게 됩니다.
즉, 계산식이 있으니 똑같은걸 넣으면 똑같은걸 빼주겠죠
해시 결과 값 중복 문제도 생기긴 하는데 뒤에 설명드리겠습니다.

---

왜 31일까
32비트 - 1 = 31 비트시프트 공간 고려
짝수일 경우 곱셉의 결과에서 overflow가 발생했을때 정보의 손실이 생김
추가적으로 32*N(개) - N 형태가 되서 빠르게 계산이 가능하다고 하네요

---

객체에 hashCode 재정의를 했을 경우 돌아가는 방식을 알아봤습니다.

그래서 그럼 HashMap은 얘를 어떻게 가져가는가
HashMap에 Put을 들어가 보시면 제네릭 타입은 적절히 적용이 될거고
``` java
public V put(K key, V value) {
    return putVal(hash(key), key, value, false, true);
}
```
이렇게 구현이 되어 있습니다.

puVal()메서드로 넘어가기 전에 hash(매개변수) 메서드를 넘겨주는데
``` java
static final int hash(Object key) {
    int h;
    return (key == null) ? 0 : (h = key.hashCode()) ^ (h >>> 16);
}
```
이런 방식으로 계산을 해주는 것 같습니다
알 수 있는건 key에 대입되는 객체의 hashCode()를 받아서 만든다는 건데
재정의를 안하게 되면 애초에 Object객체에 계산하는 다른 해시 값으로 계산이 되기 때문에 Objects에서 계산하는게 아니라서 다르게 생성되게 됩니다.

아까 언급했듯이 그러면 다른걸 넣었는데 같은 hash값이 나올 경우가 있지 않을지?에 대해서는
putVal에서 중복된 해시 값에 대해 다른 value값이 있으면 chaining해서 넣어주고 있습니다.

그럼 다시 넘어와서
``` java
final V putVal(int hash, K key, V value, boolean onlyIfAbsent, boolean evict)
```
기본적으로 생각할 수 있는 Map put 동작을 구현해놓은거 같습니다.
확인할 수 있는건
``` java
tab[i] = newNode(hash, key, value, null) 
```
``` java
Node<K,V> newNode(int hash, K key, V value, Node<K,V> next) {
    return new Node<>(hash, key, value, next);
}
Node(int hash, K key, V value, Node<K,V> next) {
    this.hash = hash;
    this.key = key;
    this.value = value;
    this.next = next;
}
```
노드 생성할 때 hash를 넣네요

이해를 위해선 이 정도만 있어도 되지 않을까 싶습니다.

자세하게 다른 글도 있어서 아래에 첨부했습니다.
[https://d2.naver.com/helloworld/831311](url)
