### ISSUE TITLE
[ITEM 15] 스레드 안전

### ISSUE THREAD

**Issue by kahyun0255** [hgh1472/ReadingStudy#13]
99페이지에서 public 가변 필드를 갖는 클래스는 일반적으로 스레드 안전하지 않다는데, 

스레드 안전이 뭐고 왜 public 가변 필드를 갖는 클래스가 안전하지 않은지 궁금합니다. 그리고 스레드가 안전하려면 어떻게 해야하는건가요??

**Comment by l2yujw** [comment]
### Thread-Safe는 많은 스레드가 공유 자원에 접근해도 프로그램이 문제 없이 돌아가는 상태입니다.
### race condition, deadlock, livelock, starvation이 발생하지 않는 동시에 공유 자원에 대한 순차적인 접근이 이루어지도록 보장하기 위함 이라고도 하네요

---

race condition -> 여러 개의 프로세스가 공유자원에 동시 접근할 때 실행 순서에 따라 결과값이 달라질 수 있는 현상
deadlock -> 두 개 이상의 스레드가 서로를 기다리면서 영원히 차단되는 상태
livelock  -> 두 개 이상의 프로세스가 서로 상대방이 진행할 수 있도록 양보하다가 무한정 대기 상태에 빠지는 현상
starvation -> 특정 프로세스의 우선순위가 낮아서 원하는 자원을 계속 할당 받지 못하는 상태

---

public 가변 필드를 갖게 될 경우 스레드가 실행되는 동안에 직접적으로 필드에 접근할 수 있어서 의도하지 않은 결과가 나오게 됩니다.

```java
public class Bank {
    public double balance;

    public Bank(double balance) {
        this.balance = balance;
    }

    public void deposit(double amount) {
        balance += amount;
    }

    public void withdraw(double amount) {
        balance -= amount;
    }
}
```
```java
public class Test implements Runnable {
    private Bank = bank;

    public Test(Bank bank) {
        this.bank = bank;
    }

    @Override
    public void run() {
        for (int i = 0; i < 5; i++) {
            bank.deposit(100);
            bank.withdraw(100);
        }
    }
}
```
```java
public static void main(String[] args) throws InterruptedException {
    Bank bank = new Bank(1000.0);

    Test test1 = new Test(bank);
    Test test2 = new Test(bank);

    Thread t1 = new Thread(test1, "Thread 1");
    Thread t2 = new Thread(test2, "Thread 2");

    t1.start();
    t2.start();

    for (int i = 0; i < 3; i++) {
        Thread.sleep(100);
        bank.balance = 5000.0;
    }

    t1.join();
    t2.join();
}
```
thread 실행 도중에 balance의 값이 5000.0으로 변경되고 
```
1000, 
+100, -100
5000! 
+100 -100
+100
5000!
-100 4900!
```
balance가 public으로 열려 있었기 때문에 직접 접근이 가능해져 문제가 위와 같이 생기게 됩니다.
따라서 private으로 변경하여 접근을 막아야 합니다.
또한 순서 보장이 안되어 +100 세번 각각 진행후 -100 세번이 진행되는 문제가 생길 수 있기 때문에 synchronized를 적용해주어야 합니다.

## Thread-Safe 방법
### 무상태, 불변
객체를 무상태로 구현하면 내부 상태나 외부 상태에 의존하지 않기 때문에 항상 Thread-Safe합니다.
객체를 불변으로 구현하면 객체가 생성된 후에도 내부 상태를 변경할 수 있기 때문에 Thread-Safe합니다.

### synchronized 사용

### Atomic Objects (AtomicInteger, AtomicLong, AtomicBoolean...)
atomic 클래스는 멀티 스레드 환경에서 원자성을 보장해줍니다.
non-blocking 방식으로 동작하며 핵심 동작 원리는 CAS(Compare And Swap) 알고리즘이라고 합니다.
https://steady-coding.tistory.com/568

### Volatile
변수에 volatile 키워드를 붙이면 CPU Cache를 사용하지 않고 Main Memory에 변수를 저장해 읽기와 쓰기 연산을 수행한다고 명시하는 것이라 합니다.
즉, 오직 하나의 쓰레드에서 읽기와 쓰기 작업을 하고 나머지 쓰레드에서는 읽기 작업만 보장되는 경우에 사용합니다.

### Concurrent Collections (CopyWriteArrayList, ConcurrentMap, ConcurrentHashMap..)
