### ISSUE TITLE
[ITEM13] 리플렉션을 사용한 clone() 메서드를 호출

### ISSUE THREAD

**Issue by yeonsu00** [hgh1472/ReadingStudy#14]
77페이지에서 "Cloneable을 구현하는 것만으로는 외부 객체에서 clone 메서드를 호출할 수 없다. 리플렉션을 사용하면 가능하지만, 100% 성공하는 것은 아니다. 해당 객체가 접근이 허용된 clone 메서드를 제공한다는 보장이 없기 때문이다."라고 했는데

리플렉션을 사용하여 외부 객체에서 clone() 메서드를 호출하는 방법이 궁금합니다. 그리고 리플렉션에 대한 설명도 부탁드릴게요!

**Comment by l2yujw** [comment]
## Clone!!
```java
public interface Cloneable {
}
```

Cloneable은 마커 인터페이스라고 하는데 자주 보셨을 예시로는 Serializable이 있습니다
즉, Cloneable에는 실제 구현 메서드가 없고 객체가 복제 가능하다 라고 표현을 해주기 위함일 뿐입니다.

---

마커인터페이스
일반적인 인터페이스와 동일하지만 사실상 아무 메소드도 선언하지 않은 인터페이스입니다.

---

Object의 clone메서드를 들어가보면
```java
@IntrinsicCandidate
protected native Object clone() throws CloneNotSupportedException;
```

Object 클래스에서 clone은 protected 되어있어서 외부에서 직접 접근을 하지 못하기 때문에 외부에서 직접 호출을 해줘야 합니다.
protected로 둔 이유는 복제는 위험할 수 있기 때문에 제어할 수 있어야 하기 때문입니다.
그래서 설계자에게 제어할 수 있는 상황을 제공합니다.
native는 다른 질문에 남겨놨습니다.

그러면 Clonable을 implements 하지 않고 직접 구현하면 되는거 아닌가?
CloneNotSupportedException 얘가 Clonable이 구현되어 있지 않으면 던져진다고 합니다.


## 리플렉션이랑 엮이면 어떻게 돌아가는가

```java
public class Person implements Cloneable {
    private String name;
    private int age;

    public Person(String name, int age) {
        this.name = name;
        this.age = age;
    }

    public String getName() {
        return name;
    }

    public int getAge() {
        return age;
    }

    @Override
    public Object clone() throws CloneNotSupportedException {
        return super.clone();
    }
}
```

제가 질문들을 Person으로 계속 테스트 돌리고 내부를 뜯어보고 있는데 이걸 예시로 하면
Clonable에서는 아무것도 구현하고 있지 않기 때문에 clone을 Override할 때 public protected private 등 자유롭게 변경이 가능합니다.

reflection으로
```java
Person original = new Person("ㅇ", 1);
Method method = person.getClass().getDeclaredMethod("clone");
method.setAccessible(true); // 접근 허용 (private도 강제로 접근할 수 있게 됌 / 기본적으로 private은 접근 불가)
Person newPerson = (Person) method.invoke(original); // original 객체의 clone() 메서드를 리플렉션으로 실행
```
이렇게 수행시킬 때 clone 메서드가 구현되어 있지 않으면 당연히 실행이 안됩니다
private이어도 따로 권한을 주지 않는 이상 접근이 안되서 불가능합니다.
찾아보니까 보안 정책으로 reflection으로 직접 접근을 못하게 하면 애초에 안먹힌다고도 하네요


# 리플렉션
자바의 런타입 메타 프로그래밍 기법으로, 런타임에 클래스의 구조(필드, 메서드, 클래스 등)을 분석하고 실행할 수 있는 기능을 제공합니다
컴파일 시점이 아닌 실행 시점에 클래스의 메서드나 필드에 접근하거나 메서드를 호출할 수 있게 해줍니다.
내부 함수들은 찾아보시는게 더 나을거 같습니다

## Class 클래스

- 클래스에 대한 정보를 얻을 때 사용하기 좋다
- Object 클래스에 있는 getClass() 메서드를 이용하는 것이 일반적이다
- 변수 목록을 Field 클래스 타입으로 받아온다
- 선언된 메서드들을 적절히 가져온다
- 선언된 생성자 정보를 적절히 가져온다

## Method 클래스

- Class 클래스의 getMethods() 메서드를 사용하거나 getDeclaredMethod() 메서드를 써야한다
- 해당 메서드에 관한 각종 정보들을 리턴함

## Field 클래스

- Class 클래스의 getField() 메서드나 getDeclaredFields() 메서드를 써야함
- 변수 관련 정보를 제공한다

---

잘못된 사례

```java
src.getClass().getName().equals("")
```

reflection에 꽂혀서 단편적으로 생각 말자 (1.022초)

```java
src instanceof ...
```

이게 있다 (0.167초)

---


# 추가적인 내용!

```java
class Person
class Man extends Person

        Person p1 = new Person("asdf", 1);
        Person p2 = new Man("asdf", 1);

        Class<? extends Person> c1 = p1.getClass();// class (test.pacakges.Person 클래스 까지의 경로)
        Class<? extends Person> c2 = p2.getClass();// class (test.pacakges.Man 클래스 까지의 경로)

        System.out.println("p1 = " + p1);
        System.out.println("p2 = " + p2);
        System.out.println("c1 = " + c1);
        System.out.println("c2 = " + c2);
        System.out.println("p1 instanceof Person = " + (p1 instanceof Person)); // 가능
//        System.out.println(c1 instanceof Person); // 불가능
        System.out.println("c1 == c2 = " + (c1 == c2)); // 가능 false
//        System.out.println(c1 == p1); // 불가능
        System.out.println("c1.equals(p1) = " + c1.equals(p1));// 가능 false

```

### 참고링크
[https://tjdtls690.github.io/studycontents/java/2023-01-27-reflection01/](url)
