### ISSUE TITLE
[ITEM 17] 불변 객체간의 내부 데이터 공유 방식

### ISSUE THREAD

**Issue by l2yujw** [hgh1472/ReadingStudy#15]
p.109에 배열은 비록 가변이지만 복사하지 않고 원본 인스턴스와 공유해도 된다고 써있습니다.
어떤 방식으로 공유가 되는지 머릿속에 안그려지더라고요..
내부 데이터 공유 방식을 예시를 들어서 설명 부탁 드릴게요!

**Comment by yeonsu00** [comment]
**불변 객체는 자유롭게 공유할 수 있음은 물론, 불변 객체끼리는 내부 데이터를 공유할 수 있습니다.**

## 내부 데이터 공유의 의미
불변 객체는 그 상태가 변경되지 않기 때문에, 동일한 데이터를 여러 객체가 공유해도 문제가 없습니다. 그래서 불변 객체끼리는 내부 데이터를 공유할 수 있습니다. 
109페이지에서 배열은 비록 **가변**이지만 복사하지 않고 원본 인스턴스와 공유해도 된다고 되어 있습니다. 이것에 대해 아래 예시를 통해 살펴보겠습니다!

## 📍 예시 - BigIntger

### BigInteger 클래스
BigInteger 클래스는 큰 정수 값을 표현하는데, 내부적으로 그 값을 두 가지 부분으로 나눕니다
- 부호 (sign): 정수 값이 양수인지 음수인지를 나타내고, int로 표현됩니다.
- 크기 (magnitude): 숫자의 절대값을 나타내고, int 배열로 표현됩니다.

### BigIntger의 negate() 메서드
BigInteger 클래스의 negate() 메서드는 부호만 반대인 새로운 BigInteger 객체를 생성합니다.
이때 숫자의 절대값을 나타내는 배열(magnitude)은 복사하지 않고 원본 BigInteger 객체와 공유합니다. 
배열 자체는 가변이지만, 불변 객체인 BigInteger는 절대 이 배열을 수정하지 않기 때문에 두 객체가 같은 배열을 가리켜도 안전하게 사용할 수 있습니다.



``` java
class BigInteger {
    private final int signum;  // 부호: 1은 양수, -1은 음수
    final int[] magnitude;     // 숫자의 절대값을 나타내는 배열

    // negate 메서드
    public BigInteger negate() {
        return new BigInteger(this.magnitude, -this.signum);
    }

    // 내부 생성자 (배열 공유를 위해 사용)
    private BigInteger(int[] magnitude, int signum) {
        this.magnitude = magnitude;  // 배열을 복사하지 않고 공유
        this.signum = signum;
    }
    (생략)
}
```

```java
public class BigIntegerExample {
    public static void main(String[] args) {
        // 1234 BigInteger 객체를 생성
        BigInteger original = new BigInteger("1234");

        // 부호만 반대인 BigInteger 객체를 생성
        BigInteger negated = original.negate();

        // 원본 BigInteger와 negated BigInteger의 정보 출력
        System.out.println("원본 값: " + original); // 1234
        System.out.println("부호 바꾼 값: " + negated);   // -1234

        // 두 객체가 동일한 magnitude 배열을 참조하는지 확인
       // 배열 자체는 가변이지만, BigInteger는 불변 객체이기 때문에 배열의 내용은 변경되지 않음
        System.out.println("같은 배열을 참조하는지 확인: " + (Arrays.equals(original.magnitude, negated.magnitude))); // true
    }
}
```

정리하자면, BigInteger 클래스에서 negate() 메서드는 새로운 BigInteger 객체를 생성하지만 magnitude 배열은 복사하지 않고 기존 배열을 그대로 참조합니다.
