### ISSUE TITLE
[ITEM 26] List<String>과 List<Object>

### ISSUE THREAD

**Issue by hgh1472** [hgh1472/ReadingStudy#17]
156P 에서
```Text
매개변수로 List를 받는 메서드에 List<String>을 넘길 수 있지만, List<Object>를 받는 메서드에는 넘길 수 없다.
```
라고 적혀있습니다.
String도 Object에 속한다고 알고 있었는데, Object 내에 String은 포함되지 않는건가요?

**Comment by kahyun0255** [comment]
제네릭의 하위타입 규칙때문에 매개변수로 List를 받는 메서드에는 List<String>을 넘길 수 있지만, List<Object>를 받는 메서드에는 넘길 수 없다고 책에 나와있는데요! 제네릭의 하위 타입 규칙이 뭔지 몰라서 찾아봤습니다!

# 제네릭의 하위 타입 규칙
   - 몇 가지 예시
      - String은 Object의 하위 타입인가? : 하위타입이다.
      - List<String>은 List의 하위 타입인가? : 하위타입이다.
      - List<String>은 List<Object>의 하위 타입인가? : 아니다. 상하관계가 없다.
→ 매개변수화 타입간에는 상하관계가 없다. <br><br>
- 매개변수화 타입은 불공변이다.
  - 제네릭은 불공변이다. :  `List<Super>`와 `List<Sub>`는 하위타입, 상위타입 그 무엇도아닌 서로 다른 타입이다. 

→ 따라서 아래 코드는 컴파일되지 않음.

```
public class Raw {
    public static void main(String[] args) {
        List<String> strings = new ArrayList<>();
				// List<String>이 List<Object>의 하위타입이 아님.
        unsafeAdd(strings, "test");
    }

    private static void unsafeAdd(List<Object> list, Object o) {
        list.add(o);
    }
}
```
 
출처 : https://velog.io/@cekim/이펙티브-자바-제네릭

---

결론적으로, 제네릭의 하위 타입 규칙때문에 매개변수화 타입간에는 상하관계가 없어서 그런거같습니다.
List<String>은 로 타입인 List의 하위 타입이지만, List<Object>의 하위타입은 아니라고 해요!
