### ISSUE TITLE
[ITEM 30] 제네릭 메서드 사용법

### ISSUE THREAD

**Issue by l2yujw** [hgh1472/ReadingStudy#18]
public static <E> Set<E> union(Set<E> s1) {} 해당 형태가 보통 제네릭 메서드가 가져가는 형태인데
전에 같은 의미이지만 다르게 표현하는 방법이 있었던걸로 기억합니다. 

틀린 예시이지만 예를 들어
public static <E extends Parent> Set<E> union(Set<E> s1) {} 
public static Set<E extends Parent> union(Set<E> s1) {}
이런 느낌으로 두 메서드는 같은 표현이다 였던거 같은데 해당 부분이 맞는 내용이라면
제네릭 메서드 내부에 들어가는 <E>나 <?>위치의 내용을 다르게 한, 의미는 같지만 다른 표현법을 알려주실 수 있을까요 

그리고 
public static <E> Set<E> union(Set<E> s1) {} 에서
각 위치에 있는 <E>의 의미를 제대로 알고 싶습니다!

**Comment by kahyun0255** [comment]
# 표현 방법
```
// 제네릭 메소드 선언
// 매개 변수 타입: T
// 리턴 타입: Box<T>
public <T> Box<T> boxing(T t) {
    Box<T> box = new Box<T>();
    box.set(t);
    return box;
}
```
기본적으로는 이런식으로 선언이 가능하다고해요!

아마 지금 `<T>` 이게 질문에서 다 사라진거같은데, 
``` 
public static <T> Set<T> union(Set<T> s1) {}
```
이걸 말하는거라고 가정하고 진행하겠습니다!!

---

**와일드카드**를 사용해서
```
public static Set<?> union(Set<?> s1) { }
```
이렇게도 선언이 가능합니다!

<br><br>

# 뜻하는 것
각각 뜻하는건 위에서도 간단하게 설명을 했지만, 

```
public <타입 파라미터, ...> 리턴타입 메소드명(매개변수, ...) { }
```

```
public *<T>* Box<T> boxing(T t) {
    Box<T> box = new Box<T>();
    box.set(t);
    return box;
}
```
이 T는 매개변수타입입니다.

그래서 타입이 다른 매개변수를 여러 개 받을거면 
```
public static *<T, U>* Set<T> union(Set<T> s1, Set<U> s2) { }
```
이런식으로 선언이 가능합니다! (멀티 타입 파라미터라고합니다.)


---
<br>

```
public <T> *Box<T>* boxing(T t) {
    Box<T> box = new Box<T>();
    box.set(t);
    return box;
}
```

이거는 리턴타입입니다. 

---
<br>

추가적으로
- E   :    Element​ 
- K   :   Key 
- N   :   Number 
- T   :   Type 
- V   :   Value 
변수명은 보통 이렇게 짓는다고 하네요!!

참고 : https://kyleyj.tistory.com/36, https://blog.naver.com/zzang9ha/222059024135
