### ISSUE TITLE
[ITEM 26] 제네릭에 대해 제가 이해한 방식이 맞는지 궁금합니다.

### ISSUE THREAD

**Issue by hgh1472** [hgh1472/ReadingStudy#19]
`List<E>` 같은 형식이 제네릭으로 이해했습니다!
`List<E>`에서 `E` 부분이 `리스트에 들어 있는 원소를 컴파일러가 E로 자동으로 형변환한다` 라고 이해하는게 맞을까요?

**Comment by kahyun0255** [comment]
`List<E>`라고 되어있으면 `.get()`을 통해서 List에서 원소를 가져올 때 자동으로 원소를 `E` 타입으로 형변환합니다! <br>
또한 제네릭은 타입을 구체적으로 지정라는 것이 아니라, 추후에 지정할 수 있도록 일반화해두는 것. 즉, 작성한 클래스 또는 메서드의 코드가 특정 데이터 타입에 얽매이지 않게 해둔 것입니다. 
그렇기때문에 객체 생성 시 실제 타입을 지정해야하고, 원소 삽입시에도 지정한 `E` 형이 아닌 다른 형의 원소를 추가하려고 하면 오류가 발생한다고 합니다! 

---

추가적으로, 호출하는 방법을 보면

제네릭 메서드는 두 가지 방식으로 호출할 수 있습니다.
1.  코드에서 타입 파라미터의 구체적인 타입을 명시적으로 지정
2.  컴파일러가 매개값의 타입을 보고 구체적인 타입을 추정

```
public <T> Box<T> boxing(T t) {
    ...
}
```
이런 제네릭 메서드가 있다고했을 때

```
1. Box<Integer> box = <Integer>boxing(100); // 타입 파라미터를 명시적으로 Integer로 지정

2. Box<Integer> box = boxing(100); // 컴파일러가 타입 파라미터를 Integer로 추정
```
위에서 설명한 두 가지 방식으로 호출할 수 있습니다.

즉, 명시적으로 지정을 하면 자동으로 타입을 변환하고, 명시적으로 지정하지 않으면 컴파일러가 추정해서 타입을 변환해주는 것 같아요! 


<br><br>

출처 : https://blog.naver.com/zzang9ha/222059024135, https://velog.io/@hyoreal51/제네릭-Generic-컬렉션-Collection
