### ISSUE TITLE
[ITEM29] 제네릭 배열 생성 오류 해결 방법

### ISSUE THREAD

**Issue by yeonsu00** [hgh1472/ReadingStudy#20]
p173에서 "제네릭 배열 생성을 제거하는 방법 중 현업에서는 첫 번째 방식을 더 선호하며 자주 사용한다. 하지만 배열의 런타임 타입이 컴파일타입 타입과 달라 힙 오염을 일으킨다"고 했는데

힙 오염이 일어나는 과정이 궁금합니다!!

**Comment by kahyun0255** [comment]
# 힙 영역
- JVM이 관리하는 프로그램 상에서 데이터를 저장하기 위해 런타임시 동적으로 할달하려 사용하는 영역
- 참조형 데이터 타입을 갖는 객체(인스턴스), 배열 등이 저장되는 공간
- 보관되는 메모리 호출이 끝나더라도 삭제되지 않고 유지된다. 어떤 참조변수도 힙 영역에 있는 인스턴스를 참조하지 않으면 그 때 GC에 의해 청소된다

# 힙 오염이란?
주로 매개변수화 타입의 변수가 타입이 다른 객체를 참조하게 되어, 힙 공간에 문제가 생기는 현상을 의미한다고해요!
즉, 컴파일 중에 정상적으로 처리되고 경고를 발생시키지 않는데, 런타임시점에 `ClassCastException`이 발생하는 문제를 나타낸다고 합니다.
1, unchecked 캐스팅을 하는 경우, 2. raw 타입과 매개변수화 타입을 같이 사용하는 경우에 힙 오염이 나타난다고해요.

# unchecked 캐스팅을 하는 경우
- @SuppressWarnings("unchecked") 애노테이션을 사용
- 타입 캐스팅 체크는 컴파일러가 하지 않음 : 오직 대응되는 참조변수에 저장할 수 있냐만 검사한다.
- 제네릭의 소거 특성 : 이로인해 컴파일이 끝난 클래스 파일의 코드에는 타입 파라미터 대신 Object가 남아있게 됩니다. 
-> 따라서 실행을 시키고 꺼내는 코드가 실행되고 나서야 런타임 캐스팅 예외가 발생한다고 합니다.

---

 추가적인 내용은 item 32에 있는 것 같아요!!

출처 : https://velog.io/@semi-cloud/Effective-Java-아이템-29-이왕이면-제네릭-타입으로-만들라#%EF%B8%8F-추가-힙-오염이란, https://inpa.tistory.com/entry/JAVA-☕-그림으로-보는-자바-코드의-메모리-영역스택-힙#heap_영역
