### ISSUE TITLE
[ITEM 31] swap 메서드 비교

### ISSUE THREAD

**Issue by hgh1472** [hgh1472/ReadingStudy#22]
188p의 `코드 31-7`에서 `swap`메서드의 두가지 방식을 비교하고 있습니다.
```java
public static <E> void swap(List<E> list, int i, int j);
public static void swap(List<?> list, int i, int j);
```
두번째 메서드가 더 나은 이유가 책에 적혀있는 `어떤 리스트든 이 메서드에 넘기면 명시한 인덱스의 원소들을 교환해줄 것이다. 신경 써야 할 타입 매개변수도 없다.`일까요?
만약 그렇다면, 첫번째 메서드는 이 문장에 왜 해당하지 않는건지 궁금합니다!
첫번째 메서드는 `List<E>`로 받기 때문에 `Number`, `Number`, `Integer` 같은 경우 오류가 나는건가요??
`어떤 리스트든 이 메서드에 넘기면 명시한 인덱스의 원소들을 교환해줄 것이다. 신경 써야 할 타입 매개변수도 없다.` 이 문장에 대해 첫번째 메서드와 두번째 메서드의 차이가 궁금해요.

**Comment by l2yujw** [comment]
```java
public static <E> void swap(List<E> list, int i, int j);
public static void swap(List<?> list, int i, int j);
```
해당 제네릭 메서들이 결국 static으로 되어 있어 있어서 메서드를 공유하게 됩니다.
1번 같은 경우는
```java
swap(List<Integer> 형식, i, j);
Integer를 최초로 활용하게 되면 메서드가
public static void swap(List<Integer> list, int i, int j)
이렇게 고정이 됩니다.
이 상태에서 다음을 실행시키면
swap(List<Double> 형식, i, j);
이미 E를 Integer로 고정을 했기 때문에 컴파일 오류가 나게 됩니다.
```
두번째 메서드가 더 나은 이유가 그럼 나오게 되는데요
```java
swap(List<Integer> 형식, i, j);
public static void swap(List<?> list, int i, int j);
swap(List<Double> 형식, i, j);
public static void swap(List<?> list, int i, int j);
```
와일드 카드 형식이기 때문에 고정되지 않고 계속해서 활용이 가능해집니다.

주의할 점은 와일드 카드 형식이기 때문에 추가 수정은 불가능합니다.

즉, 첫번째는 특정 타입에 대한 타입 안정성을 줄 수 있고
두번째는 모든 타입에서 사용할 수 있도록 할 수 있습니다.
