### ISSUE TITLE
[ITEM 34] 정수 열거 패턴과 열거 타입의 컴파일

### ISSUE THREAD

**Issue by hgh1472** [hgh1472/ReadingStudy#23]
209, 210P를 보면 `정수 열거 패턴`과 `열거 타입`의 차이점이 있습니다.
- `정수 열거 패턴` : 컴파일 하면 그 값이 클라이언트 파일에 그대로 새겨진다. 따라서 상수의 값이 바뀌면 클라이언트도 반드시 다시 컴파일 해야한다.
- `열거 타입` : 열거 타입에 새로운 상수를 추가하거나 순서를 바꿔도 다시 컴파일 하지 않아도 된다. 상수 값이 클라이언트로 컴파일되어 각인되지 않기 때문이다.

여기서 말하는 클라이언트를 어떻게 이해하는게 맞을까요?
`정수 열거 패턴`일 경우, 실행 파일 자체가 특정 상수 '값'에 맞춰져 있기 때문에 값이 바뀌면 다시 컴파일 해야 할 필요가 있다는 걸까요?

**Comment by yeonsu00** [comment]
## 📌 클라이언트의 의미

제가 생각했을 때 여기서 말하는 **클라이언트**는 **열거 타입이나 정수 열거 패턴을 사용하는 모든 코드**를 의미하는 것 같습니다.

예시 코드를 보겠습니다!

### 열거 타입

```java
//열거 타입
public enum PhaseEnum {
    START,
    MIDDLE,
    END
}
```

```java
//열거 타입을 사용하는 클라이언트 코드
public class EnumClient {
    public static void main(String[] args) {
        PhaseEnum phase = PhaseEnum.START;
        System.out.println("현재 단계: " + phase);  // "현재 단계: START" 출력
    }
}
```

### 정수 열거 패턴

```java
//정수 열거 패턴
public class Phase {
    public static final int START = 0; 
    public static final int MIDDLE = 1;
    public static final int END = 2;
}
```

```java
//정수 열거 패턴을 사용하는 클라이언트 코드
public class IntegerEnumClient {
    public static void main(String[] args) {
        int phase = Phase.START;
        System.out.println("현재 단계: " + phase);  // "현재 단계: 0" 출력
    }
}
```


<br>

## 📌 정수 열거 패턴일 경우 값이 바뀌면 다시 컴파일 해야 하는 이유

**정수 열거 패턴**을 사용할 경우, **상수 값은 클라이언트 코드에 직접 삽입**됩니다. 예를 들어 컴파일 시, `Phase.START`가 0으로 정의되어 있으면, **클라이언트 코드에서는 이 값을 직접 사용**하게 됩니다.  즉, **상수 값이 클라이언트의 실행 파일에 하드코딩**된다는 것을 의미합니다.

이 경우, 상수의 순서나 값이 변경되면 **클라이언트 코드도 영향을 받게 됩니다**.

아래 예시 코드에서 `START`의 값을 0에서 3으로 변경해서 발생하는 문제를 살펴보겠습니다.

```java
//정수 열거 패턴
public class Phase {
    public static final int START = 3; // 값이 3으로 변경됨
    public static final int MIDDLE = 1;
    public static final int END = 2;
}
```

```java
//클라이언트 코드
int currentPhase = Phase.START;
```

일부 로직에서 `Phase.START`를 0으로 간주하고 처리하기 때문에 **런타임 오류**가 발생할 수 있습니다. 그래서 **클라이언트 코드를 다시 컴파일**해야 합니다.

그래서 이 방법은 **유지보수성과 확장성 측면에서** 굉장히 **비효율적**이고, **오류 발생 가능성**을 높일 수 있습니다.
