### ISSUE TITLE
[ITEM 42] 열거 타입 생성자, 람다

### ISSUE THREAD

**Issue by kahyun0255** [hgh1472/ReadingStudy#24]
257페이지에서 `열거 타입 생성자에 넘겨지는 인수들의 타입도 컴파일타임에 추론된다. 따라서 열거 타입 생성자 안의 람다는 열거 타입의 인스턴스 멤버에 접근할 수 없다`고 하는데,

`열거 타입 생성자에 넘겨지는 인수들`이 예시가 없어서 잘 이해가 안됩니다! 예시를 들어주실 수 있나요??

또한 왜 열거 타입 생성자 안의 람다는 열거 타입의 인스턴스 멤버에 접근할 수 없다는지도 자세히 설명해주세요!!

**Comment by hgh1472** [comment]
## 열거 타입 생성자에 넘겨지는 인수
먼저 책 `코드42-4` 예시를 확인해볼게요.
```java
public enum Operation {
    // 인스턴스
    PLUS("+", (x, y) -> x + y),
    MINUS("-", (x, y) -> x - y),
    TIMES("*", (x, y) -> x * y),
    DIVIDE("/", (x, y) -> x / y);

    // 필드
    private final String symbol;
    private final DoubleBinaryOperator op;

    // 생성자
    Operation(String symbol, DoubleBinaryOperator op) {
        this.symbol = symbol;
        this.op = op;
    }

    public double apply(double x, double y) {
        return op.applyAsDouble(x,y);
    }
}
```
제가 이해한 방식으로 설명 드리겠습니다! 일단 `Operation` enum을 하나의 클래스라고 생각을 해볼게요.
`Operation`은 필드로 `String symbol`과 `DoubleBinaryOperator op`를 가지고 있어요. 그리고 apply 메서드도 구현되어 있습니다.
그렇다면 저희가 `Operation` 객체를 생성하려고 하면 다음과 같이 코드를 작성하게 될거에요.
```java
// DoubleBinaryOperator는 구현되어 있다고 가정
Operation plus = new Operation("+", DoubleBinaryOperator.PLUS);
Operation minus = new Operation("-", DoubleBinaryOperator.MINUS);
Operation times = new Operation("*", DoubleBinaryOperator.TIMES);
Operation divide = new Operation("/", DoubleBinaryOperator.DIVIDE);
```
`plus`를 예시로 들면 질문하셨던 `생성자에 넘겨지는 인수`는 `"+"`와 `,DoubleBinaryOperator.PLUS`가 됩니다.
하지만 여기까지는 일반 객체였을 때 저희가 사용하는 방식이 됩니다. 하지만 저희가 **이 코드를 사용할 때마다 Operation을 생성하는 것은 불필요한 작업**이에요. `plus`의 `symbol`과 `apply`는 바뀌지 않는 내용이기 때문에 싱글톤으로 관리하여, `plus`가 필요한 곳에서 가져와서 사용하는 것이 좋은 방향으로 느껴집니다. 따라서 `enum`으로 `Operation`을 관리하게 됩니다. ([ITEM 3] private 생성자나 열거 타입으로 싱글턴임을 보증하라)
그렇다면 enum에서 내가 필요한 `plus, minus, times, divide`는 어디에 관리하냐면, 예시 코드에 인스턴스 부분입니다. 마치 `PLUS`라는 객체를 생성해서 하나의 싱글톤으로 관리하게 됩니다. 그래서 `PLUS("+", (x, y) -> x + y)` 이 코드가 생성자라고 생각합니다.
결론적으로 예시에서 `열거 타입 생성자에 넘겨지는 인수`는 `"+", (x, y) -> x + y`를 말합니다.

---
## 열거 타입 생성자 안의 람다는 열거 타입의 인스턴스 멤버에 접근할 수 없는 이유
위의 예시 코드에서 인스턴스 멤버는 `PLUS`, `MINUS`, `TIMES`, `DIVIDE`가 됩니다. 이 인스턴스들은 생성자를 통해 만들어집니다.
결국 생성자 안의 람다 내에서 인스턴스 멤버에 접근하는 것은, 실제로 enum 객체들이 만들어지기 전에 접근하는 것과 같기 때문에 이렇게 설명하였다고 생각해요!
