### ISSUE TITLE
[ITEM 43] 한정적 참조와 비한정적 참조

### ISSUE THREAD

**Issue by yeonsu00** [hgh1472/ReadingStudy#25]
260, 261페이지에서 `인스턴스 메서드를 참조하는 유형 중 하나는 수신 객체를 특정하는 한정적 인스턴스 메서드 참조이고, 다른 하나는 수신 객체를 특정하지 않는 비한정적 인스턴스 메서드 참조다` 라고 했는데

한정적 참고와 비한정적 참고가 정확히 이해되지 않습니다! 예시 코드와 함께 설명 부탁드립니다!!!

**Comment by hgh1472** [comment]
우선 `인스턴스 메서드`를 참조한다는 것은 말 그대로 특정 인스턴스의 메서드를 참조하는 것입니다.
그럼 여기서 `한정적 인스턴스 메서드 참조`와 `비한정적 인스턴스 메서드 참조`로 나뉘게 되는데요, 이 때 `한정적`과 `비한정적`의 차이는 **메서드를 참조할 외부 인스턴스의 존재 유무**에 따라 나뉘게 됩니다.
**이미 존재하는 인스턴스의 메서드를 사용**하므로 `한정적`**, 특정 타입인 것만 알고 특정 인스턴스에 대해서까지는 상관없다**면 `비한정적`입니다.

책의 예시 코드를 봐볼게요.
```java
Consumer<Instant> c;
// 1
c = Instant.now()::isAfter

// 2
Instant. then = Instant.now();
c = t -> then.isAfter(t);
```
1, 2 둘 다 같은 내용이지만 1번은 메서드 참조, 2번은 람다식입니다. 2번 내용을 보면 `then`이라는 인스턴스를 생성한 후, `then`의 isAfter 메서드를 참조하고 있어요. 즉, `then`이라는 인스턴스에 한정적이라고 볼 수 있습니다. 따라서 이를 메서드 참조로 나타낸 `Instant.now()::isAfter`는 `Instant.now()`가 생성한 인스턴스에 한정적이에요. 좀 더 이해하기 쉽게 1번 코드를 수정하면 이렇게 나타낼 수 있어요.
```java
Consumer<Instant> c;
Instant then = Instant.now();
c = then::isAfter;

책의 비한정적 인스턴스 메서드 참조 예시는 다음과 같아요.
```java
Consumer<String> c;
// 1
c = String::toLowercase;

// 2
c = str -> str.toLowerCase;
```
이 때 `str -> str.toLowerCase`를 보면, 어떤 String이 들어오든 상관없습니다. 특정 인스턴스에 한정적이지 않고, String 타입이라는 것만 알고 있어요. 그래서 메서드 참조 코드도 `String::toLowerCase`로 나타내는데 타입만 나타내고 있습니다.

즉, **`한정적`과 `비한정적`의 차이는 외부 인스턴스에 한정적인지**를 나타낸다고 생각합니다!

[메서드 참조 참고](https://ryumodrn.tistory.com/103)
