### ISSUE TITLE
[ITEM 3] Reflection API

### ISSUE THREAD

**Issue by kahyun0255** [hgh1472/ReadingStudy#3]
23페이지에서 private 생성자로 싱글턴 패턴을 만들때 예외인 권한이 있는 클라이언트는 리플렉션 API인 AccessibleObject.setAccessible을 사용해 private 생성자를 호출할 수 있다는데 리플렉션 API가 뭔가요??

**Comment by hgh1472** [comment]
먼저 코드로 예시를 먼저 들어볼게요.
```java
Elvis instance1 = Elvis.getInstance();
Class<?> class = Elvis.class;
Constructor<?> constructor = class.getDeclaredConstructor();
constructor.setAccessible(true);
Elvis instance2 = (Elvis) constructor.newInstance();
```
위 코드에서 instance1과 instance2는 서로 다르다고 합니다.

Reflection API는 런타임에서 특정 클래스, 메서드, 필드 등의 정보에 접근할 수 있게 하는 Java API입니다. 애플리케이션이 실행될 때 JVM 메모리 내에 .class 파일들이 static 영역에 올라오는데, 이 영역에 접근해 특정 클래스에 대한 정보를 얻어냅니다.
이를 통해 Elvis 클래스 타입을 얻었을 때 `getDeclaredConstructor()` 메서드를 통해 생성자에 접근할 수 있습니다. 이후 `Constructor` 객체의 `setAccessible()` 메서드를 통해 접근 가능하게 변경하면 private 임에도 불구하고 새로운 인스턴스를 생성할 수 있습니다. 하지만 실제로 저희가 코드를 작성할 때 Reflection API를 활용할 일은 거의 없고, 구체적인 클래스가 정해지지 않은 상황에서 코딩을 할 일은 거의 없습니다.

위 내용들을 보면 Reflection API는 저희가 작성한 모든 것들을 마법처럼 건너뛰는 것 같지만, 대표적으로 성능 오버헤드 단점이 있습니다. 컴파일 타임이 아닌, 런타임에 동적으로 타입을 분석하고 정보를 가져오기 때문에 JVM을 최적화할 수 없다고 합니다. 또한 private 필드, 메서드 등에 접근하기 때문에 추상화가 깨지게 됩니다.

결국 Reflection API는 애플리케이션 개발보다는 프레임워크나 라이브러리에 주로 사용됩니다. 프레임워크나 라이브러리는 사용자가 어떤 클래스를 만들지 예측할 수 없기 때문에 동적으로 해결하기 위해 Reflection API를 활용한다고 합니다. 실제로 Spring의 Spring Container의 BeanFactory에서 사용됩니다.

추가로 궁금하신 사항 있으면 코멘트 남겨주세요!

참조
[Reflection API - Tecoble](https://tecoble.techcourse.co.kr/post/2020-07-16-reflection-api/)
