### ISSUE TITLE
[ITEM 1] 인스턴스 통제 

### ISSUE THREAD

**Issue by yeonsu00** [hgh1472/ReadingStudy#4]
9페이지에서 인스턴스 통제는 플라이웨이트 패턴의 근간이 되며, 열거 타입은 인스턴스가 하나만 만들어짐을 보장한다는 게 무슨 뜻인가요?

**Comment by hgh1472** [comment]
일단 제가 생각한 책에서의 '인스턴스 통제'는 정적 팩터리 메서드를 통해 인스턴스 반환을 결정하는 것이라고 생각해요.
이 때 플라이웨이트 패턴은 재사용 가능한 객체 인스턴스를 공유시켜 메모리 사용량을 최소화하는 패턴이라고 합니다. 자주 변하는 속성과 변하지 않는 속성을 분리하고 변하지 않는 속성을 캐시하여 재사용해 메모리 사용을 줄이는 방식으로 사용됩니다. 즉, 변하지 않는 속성은 굳이 새로 생성하지 않고 반환하고 변하는 속성은 새로 생성하여 반환하는 식으로 보입니다.
따라서 정적 팩터리 메서드를 사용한 '인스턴스 통제'를 통해 **변하는 속성과 변하지 않는 속성에 따라 인스턴스를 반환할 수 있습니다.**
그리고 열거 타입은 enum 클래스로 상수를 나타내는 클래스라고 할 수 있습니다. 예를 들어 우리는 가끔 다음과 같은 형식으로 클래스 내에서 상수를 사용합니다.
```java
class Adder {
    private final static int plus = 1;
    private final static int minus = 2;
    // ...
}
```
위처럼 사용하는 대신 아예 상수만을 다루는 enum 타입 클래스가 존재합니다.
```java
enum Calculation {
    ADD(1),
    MINUS(2);
    private final int command;
    Calculation(int command) {
        this.command = command;
    }

    public int getValue() {
        return command;
    }
}
```
이 때 enum 클래스는 상수 값과 같이 유일하게 하나의 인스턴스가 생성되어 사용됩니다. enum의 상수값은 힙 영역에 저장됩니다. 따라서 String처럼 스택 영역에 있는 변수들이 힙 영역에 있는 데이터의 주소값을 저장함으로써 참조 형태를 띄게 됩니다. 그리고 enum은 싱글톤 형태로 만들어진다고 합니다.
