### ISSUE TITLE
[ITEM 2] 빌더와 다른 패턴들의 차이점

### ISSUE THREAD

**Issue by l2yujw** [hgh1472/ReadingStudy#5]
빌더의 형식이 데코레이터 패턴과 유사한데 이 둘의 차이점과 각각 어떤 상황에 사용을 해야 하나요?

마찬가지로 빌더와 팩토리 패턴의 차이점, 그리고 핵심 정리 부분에서 말하는 '매개변수가 많다면'이 통상적으로 어느 정도 인가요?

**Comment by hgh1472** [comment]
기존에 데코레이터 패턴에 대해서 추가적으로 한 번 찾아봤습니다!
제가 찾아보며 생각했을 때 우선 데코레이터 패턴은 기존 객체에 대해 기능의 확장이나 변경이 필요할 때 상속하는 하위 클래스 대신 사용할 수 있는 패턴이라고 생각합니다. 예를 들어 하나의 객체 A가 존재한다고 할 때, 이 객체의 기능이 확장될 수 있습니다. 이 때 확장된 기능이 X, Y, Z라고 해보겠습니다. 만약 확장된 기능에 따른 하위 클래스를 만든다고 한다면, 우리는 'A+X', 'A+Y', 'A+Z', A+X+Y' ... 와 같이 만들어야 하는 상황이 올 수 있습니다.
이 때 X, Y, Z만 구현하고, 원본 클래스에 단순히 넣어주는 방식으로 사용합니다.
```java
new Z(new X(new A()));
```
위처럼 원본 객체 생성자(`new A()`)를 장식자 생성자(`new Z()`, `new X()`)가 래핑하는 형태로 진행됩니다.
반면 빌더의 경우 생성자에서 매개변수가 많을 때 이점을 얻기 위해 사용하는 패턴입니다. 즉, 기능의 확장이 아닌 생성자에서 이점을 얻기 위해 사용하는 패턴이라고 생각됩니다.

다음으로 팩토리 패턴과 빌더 패턴은 결국 둘 다 객체의 생성과 관련한 것이지만, 팩토리 패턴은 싱글톤이나 매개변수에 자유롭게 생성할 수 있다는 것에 장점이 있습니다. 예를 들어 조회한 Entity를 DTO로 변환할 경우, 매개변수를 Entity 그대로 넣어 DTO로 변환할 수 있습니다.
대신 빌더 패턴은 매개변수에서 비록 자유롭지 못하지만, 인자가 여러 개가 되더라도 작성하고 읽기에 매우 편리하다는 것에 장점이 있는 것 같습니다.
빌더 패턴을 사용하면 코드가 장황해서 약 매개변수가 4개 이상은 되어야 이점이 있다고 합니다. 하지만 API는 갈수록 확장되는 경향이 있기 때문에 무조건적으로 4개 이상부터 사용할 필요는 없을 것 같습니다. 그리고 Spring에서 Lombok을 사용할 경우, 손쉽게 Builder 패턴을 적용할 수 있기 때문에 Builder 패턴은 사용하는 것도 좋을 것 같습니다!
