### ISSUE TITLE
[ITEM 7] 객체 참조 null 처리해야 하는 경우들

### ISSUE THREAD

**Issue by l2yujw** [hgh1472/ReadingStudy#6]
38p ' 객체 참조를 null 처리해야 하는 일은 예외적인 경우여야 한다'
1. 예외적인 경우가 추가적으로 어떤 것들이 있는지
2. Stack 외에도 자기 메모리를 직접 관리하는 클래스의 종류
3. 유효 범위 밖으로 밀어낸다는 것이 어떻게 동작 시킨다는 것인지
4. 콜백의 해지 예시와 해지 시 주의해야 할 점이 있다면 어떤 것인지

이렇게 이해 안되는 부분들이 있는데 알려주실 수 있을까용

**Comment by hgh1472** [comment]
1. 책에서 말하는 예외적인 경우는 Stack처럼 메모리를 직접 관리하는 경우라고 생각합니다.
2. 스택 외에도 큐나 아니면 객체 풀 같은 경우가 해당되지 않을까 싶습니다.
3. 저는 이 문장을 읽을 때 객체의 범위를 바꾸는 것인가 했는데, 책에서 ITEM 57을 살짝 살펴보았을 때, 객체의 범위를  최소화하라는 뜻으로 느껴집니다!
4. 콜백 해지 예시 (필드에 콜백 할당)

예시 코드가 길어서 자세한 내용은 레포에 푸시해서 올리겠습니다! 간단하게 테스트 코드만 살펴보겠습니다. `DatabaseManager` 는 콜백 인터페이스인 `Connection` 을 필드로 가지고 있습니다. `Connection` 인터페이스는 클라이언트 측엥서 정의되고 `CustomDatabaseManager` 에 할당됩니다.

```java
@DisplayName("콜백으로 정의된 인터페이스를 필드에 직접 가지고 있으면 메모리누수")
	@Test
	public void memoryLeak() {

		Connection connection = createConnection("Memory Leak Connection");

		DatabaseManager databaseManager = new CustomDatabaseManager(connection);
		databaseManager.execute("SELECT * FROM TEST");

		connection = null; // 참조해제 시도

		System.gc();
		System.runFinalization();
		
		Thread.sleep(3000);

		assertNotNull(((CustomDatabaseManager) databaseManager).getConnection());
	}

```

단순하게 클라이언트에서 `connection` 에 null을 할당할 수 있습니다. 그 뒤 GC가 수거하길 기다리지만 수거하지 않습니다. 즉, `databaseManager`의 `connection`은 다시 사용되지 않아도 gc의 대상이 되지 않습니다. 이 경우 메모리 누수를 방지하는 방법은 `databaseManager`에게 직접 `connection`에 null을 할당하라고 명령하는 것입니다.

```java

	@DisplayName("필드에 참조된 콜백 인터페이스를 참조해제 하는 방법")
	@Test
	public void callbackMemory() {
		Connection connection = createConnection("Memory Leak Connection");
		DatabaseManager databaseManager = new CustomDatabaseManager(connection);

		((CustomDatabaseManager) databaseManager).deConnect();
		connection = null;

		assertNull(((CustomDatabaseManager) databaseManager).getConnection());
	}

```

다른 방식으로 콜백을 등록할 수 있는데 `WeakHashMap` 을 사용하는 것입니다.

```java

	@DisplayName("WeakHashMap 을 사용해서 메모리 누수 방지하는 방법")
	@Test
	public void weakHashMap() throws InterruptedException {
		Connection connection = createConnection("using WeakHashMap");
		DatabaseManager databaseManager = new CacheDatabaseManager(connection);

		connection = null; // 참조해제 시도

		System.gc();
		System.runFinalization();

		Thread.sleep(3000);

		assertThrows(RuntimeException.class, ((CacheDatabaseManager) databaseManager)::getConnection);
	}
```

`WeakHashMap` 을 사용할 경우 클라이언트에서 null을 할당해도 gc의 대상이 될 수 있습니다.

주의할 점은 첫번째 예시와 같이 사용할 경우 직접 해당 객체에서 null로 변경해야 한다는 점이 될 수 있습니다.
객체에 대한 자세한 코드는 push해두었습니다!

---
참조 : https://javabom.tistory.com/14
