### ISSUE TITLE
[ITEM 7] 배열 크기를 많이 늘린다면 어떻게 되는지

### ISSUE THREAD

**Issue by l2yujw** [hgh1472/ReadingStudy#7]
살짝 별개의 질문이긴 한데
Stack에서 많은 push()로 인해 배열이 계속 확장이 됐고
이후 대부분의 객체를 참조 해제 했을 때
이미 확장된 배열의 크기가 메모리에 영향을 주는 부분이 있나요?
해제 과정에서 배열의 크기를 줄이고 새로 복사해서 내보내지 않을까 생각을 해보긴 했는데, 
영향이 있다면 영향을 줄이는 방법이랑 있어도 굳이 할 필요가 없는지 같은 내용이 궁금합니다!

해당 내용이 참조 해제와 관련이 있으면 관련 내용도 알고 싶습니다!

**Comment by hgh1472** [comment]
배열의 크기가 확장된 상태라면, 배열의 크기에 따라 갖게되는 참조변수는 결국 존재하기 때문에, 객체 자체의 메모리는 GC에 의해 수거되지만 단순한 참조변수는 사라지지 않는 것 같습니다.
실제로 Stack 구현체의 코드를 살펴본 결과 다음과 같습니다. Stack 구현체는 Vector 클래스를 상속받고 있기 때문에 실제로 `pop()` 메서드 실행시 아래 메서드가 실행됩니다.
![image](https://github.com/user-attachments/assets/7c080765-137e-419a-b1a2-31ab434f8b7a)
스택의 경우, j는 0이 되기 때문에 단순히 배열의 해당 참조를 null로 바꿔주기만 하고 있는 것 같습니다. Vector 클래스 내에 원소의 개수만큼 배열의 사이즈를 조정하는 `trimToSize()` 메서드가 존재하기는 합니다. 그런데 Stack의 `pop()`메서드에서 따로 실행을 시키지는 않고 있습니다.
단순히 제 생각으로 짐작해본 결과.. 저장되는 객체에 비해 배열의 참조변수는 메모리 사용량이 비교적 적기도하고, pop 실행 시 마다 사이즈를 재조정하기에는 오버헤드가 더 크기 때문이 아닐까 싶습니다.
